### ISSUE TITLE
Cannot reload with command

### ISSUE THREAD

**Issue by TowardtheStars** [senseiwells/CustomNameTags#3]
After executing command `/nametag reload`, the result is always: `An unexpected error occurred trying to execute that command`.
And custom file copied from example cannot be loaded into game.

|Component| Version
|---|---
|Minecraft | 1.20.2
|Fabric Loader | 0.14.25
|Fabric Language Kotlin | 1.10.16+kotlin.1.9.21
|CustomNameTags| 0.1.2

**Comment by senseiwells** [comment]
Please try [this version](https://cdn.discordapp.com/attachments/967529963106492448/1181624452342087783/CustomNameTags-0.1.3.jar?ex=6581bc86&is=656f4786&hm=72887d136040e61a27dcdf954162e8a66b30ef92c4c329c2f55452ddd30d02f0&). 

I have also updated the example (as there was a bug in placeholder API that caused it to error).
Let me know if that fixes the error.
