### ISSUE TITLE
Name tags are in the wrong position when viewed from above 

### ISSUE THREAD

**Issue by GoldAndGlory** [senseiwells/CustomNameTags#6]
Offset

**Comment by senseiwells** [comment]
This is because of how vanilla implements text displays and unfortunately it's something that I can't really fix.

I have already spent countless hours trying to.

**Comment by GoldAndGlory** [comment]
Just in case you haven’t tried, are you doing centered or horizontal billboards? Horizontal doesn’t offset them

**Comment by senseiwells** [comment]
Yes, I have tried this. Horizontal billboards looks significantly worse in my opinion, if a player is above/below you, you have no indication that they are.

**Comment by GoldAndGlory** [comment]
This offset doesn’t seem to be present in TAB using text displays:

https://www.youtube.com/watch?v=NaFw6lTt67Y

**Comment by senseiwells** [comment]
I have rewritten the entire mod and this is now fixed in 9d3e80b0fe74e5ca728473d29e5322f260a930f8
